#!/bin/bash

#Simple helper script to visualise a whole bunch of plots

outDir=$1
inDir=$2
coeff=$3
[[ $1 ]] || outDir="plots"
[[ $2 ]] || inDir="outputs"
[[ $3 ]] || coeff="0.65"

# echo "COEFF = $coeff"

[[ -d $outDir ]] || mkdir $outDir

rm $outDir/* 2>/dev/null

for n in `seq 0 8`
do
    # echo -n "$n/8..."
    visualise.sh  neighbours --neighbours=$n --output-dir=$inDir --save=$outDir/n$n --coeff=$coeff --no-show
done